### PR TITLE
Bugfix in shim-eth-vlan, locking issue, fixes #721

### LINKED ISSUE #721: Shim_eth_vlan sometimes decide to oops during ipcm Ctrl-c
Branch: Pristine-1.3
Sometimes, when i Ctrl-C to stop the ipcm, oops.

```
Stack trace:
Aug 28 04:58:19 alpha kernel: [  794.438505] rina-rmt(DBG): [n1_port_destroy] Destroying N-1 port ffff8800219ad200 (port-id = 11)
Aug 28 04:58:19 alpha kernel: [  794.438511] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002e1d11c0 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.438517] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002e1d11c0 destroyed
Aug 28 04:58:19 alpha kernel: [  794.438521] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002dbc4bc0 stopped
Aug 28 04:58:19 alpha kernel: [  794.438525] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002dbc4bc0 destroyed
Aug 28 04:58:19 alpha kernel: [  794.438530] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002e1d4040 stopped
Aug 28 04:58:19 alpha kernel: [  794.438746] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002e1d4040 destroyed
Aug 28 04:58:19 alpha kernel: [  794.438750] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002e5a1e40 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.438753] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002e5a1e40 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441112] rina-dtp(DBG): [dtp_destroy] Instance ffff88003d3a5f40 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441118] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002d48c240 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.441121] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002d48c240 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441137] rina-dtcp(DBG): [dtcp_destroy] Instance ffff88002e5a1440 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441141] rina-dt(DBG): [dt_destroy] Instance ffff88002decf640 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441145] rina-cidm(DBG): [cidm_release] Bitmap release completed successfully
Aug 28 04:58:19 alpha kernel: [  794.441148] rina-efcp(DBG): [efcp_destroy] EFCP instance ffff88002decf080 finalized successfully
Aug 28 04:58:19 alpha kernel: [  794.441152] rina-efcp(DBG): [efcp_connection_destroy] EFCP connection destroy called
Aug 28 04:58:19 alpha kernel: [  794.441158] rina-rfifo(DBG): [rfifo_destroy] FIFO ffff88002e380440 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441162] rina-rmt(DBG): [rmt_qgroup_destroy] Qgroup for port: 8 destroyed...
Aug 28 04:58:19 alpha kernel: [  794.441166] rina-rmt(DBG): [n1_port_destroy] Destroying N-1 port ffff88002d4691c0 (port-id = 8)
Aug 28 04:58:19 alpha kernel: [  794.441170] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002de3e940 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.441173] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002de3e940 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441176] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002dbc4d40 stopped
Aug 28 04:58:19 alpha kernel: [  794.441179] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002dbc4d40 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441182] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002dbc4e40 stopped
Aug 28 04:58:19 alpha kernel: [  794.441185] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002dbc4e40 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441188] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002e5a10c0 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.441190] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002e5a10c0 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441196] rina-dtp(DBG): [dtp_destroy] Instance ffff88003d140a40 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441199] rina-rtimer(DBG): [__rtimer_stop] Timer ffff88002e1d45c0 is not pending, can't stop it
Aug 28 04:58:19 alpha kernel: [  794.441202] rina-rtimer(DBG): [rtimer_destroy] Timer ffff88002e1d45c0 destroyed
Aug 28 04:58:19 alpha kernel: [  794.441212] rina-dtcp(DBG): [dtcp_destroy] Instance ffff88002dbc4c40 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441215] rina-dt(DBG): [dt_destroy] Instance ffff88002e4cb400 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441218] rina-cidm(DBG): [cidm_release] Bitmap release completed successfully
Aug 28 04:58:19 alpha kernel: [  794.441221] rina-efcp(DBG): [efcp_destroy] EFCP instance ffff880000f0d7c0 finalized successfully
Aug 28 04:58:19 alpha kernel: [  794.441224] rina-ipcp-utils(DBG): [name_fini] Name at ffff88003d3b5a60 finalized successfully
Aug 28 04:58:19 alpha kernel: [  794.441227] rina-ipcp-utils(DBG): [name_destroy] Name at ffff88003d3b5a60 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441230] rina-ipcp-utils(DBG): [name_fini] Name at ffff88003d375360 finalized successfully
Aug 28 04:58:19 alpha kernel: [  794.441233] rina-ipcp-utils(DBG): [name_destroy] Name at ffff88003d375360 destroyed successfully
Aug 28 04:58:19 alpha kernel: [  794.441265] BUG: unable to handle kernel NULL pointer dereference at 0000000000000020
Aug 28 04:58:19 alpha kernel: [  794.443738] IP: [<ffffffffa04a5448>] find_flow+0x38/0x70 [shim_eth_vlan]
Aug 28 04:58:19 alpha kernel: [  794.445128] PGD 3d3ae067 PUD 2e24f067 PMD 0
Aug 28 04:58:19 alpha kernel: [  794.446289] Oops: 0000 [#1] SMP
Aug 28 04:58:19 alpha kernel: [  794.447369] Modules linked in: cdrr(O) normal_ipcp rina_default_plugin shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp mrp llc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc snd_intel8x0 crc32_pclmul ghash_clmulni_intel ppdev aesni_intel snd_ac97_codec joydev i2c_piix4 i2c_core aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd snd_pcm snd_timer snd psmouse pcspkr evdev serio_raw soundcore ac97_bus video ac processor parport_pc parport battery button thermal_sys autofs4 ext4 crc16 mbcache jbd2 hid_generic usbhid hid sg sd_mod crc_t10dif crct10dif_generic sr_mod cdrom ata_generic crct10dif_pclmul crct10dif_common ata_piix ahci libahci crc32c_intel ohci_pci ehci_pci ohci_hcd ehci_hcd pcnet32 mii usbcore usb_common e1000 libata scsi_mod [last unloaded: rina_default_plugin]
Aug 28 04:58:19 alpha kernel: [  794.465727] CPU: 0 PID: 6442 Comm: ipcm Tainted: G           O  3.15.0 #138
Aug 28 04:58:19 alpha kernel: [  794.467128] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
Aug 28 04:58:19 alpha kernel: [  794.469364] task: ffff88003d118ba0 ti: ffff88003d188000 task.ti: ffff88003d188000
Aug 28 04:58:19 alpha kernel: [  794.472131] RIP: 0010:[<ffffffffa04a5448>]  [<ffffffffa04a5448>] find_flow+0x38/0x70 [shim_eth_vlan]
Aug 28 04:58:19 alpha kernel: [  794.473619] RSP: 0018:ffff88003d18beb0  EFLAGS: 00010013
Aug 28 04:58:19 alpha kernel: [  794.474370] RAX: 0000000000000286 RBX: 0000000000000000 RCX: 0000000000000000
Aug 28 04:58:19 alpha kernel: [  794.475192] RDX: ffff88003d1cb768 RSI: 0000000000000000 RDI: ffff88003d1cb764
Aug 28 04:58:19 alpha kernel: [  794.476015] RBP: ffff88003d1cb700 R08: 0000000000000286 R09: 000000000000fffe
Aug 28 04:58:19 alpha kernel: [  794.476840] R10: ffff88003d3b50c0 R11: 00000000010a903f R12: 0000000000000007
Aug 28 04:58:19 alpha kernel: [  794.477678] R13: ffff88003d1cb764 R14: ffff88001275e000 R15: 0000000000000000
Aug 28 04:58:19 alpha kernel: [  794.478484] FS:  00007f0e3268f740(0000) GS:ffff88003fc00000(0000) knlGS:0000000000000000
Aug 28 04:58:19 alpha kernel: [  794.479753] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Aug 28 04:58:19 alpha kernel: [  794.480479] CR2: 0000000000000020 CR3: 000000002e1d0000 CR4: 00000000000406f0
Aug 28 04:58:19 alpha kernel: [  794.481290] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Aug 28 04:58:19 alpha kernel: [  794.482141] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Aug 28 04:58:19 alpha kernel: [  794.482952] Stack:
Aug 28 04:58:19 alpha kernel: [  794.483475]  ffff88003d1cb700 ffff88001275e150 ffff88001275e408 ffff88001581a700
Aug 28 04:58:19 alpha kernel: [  794.484725]  ffffffffa04a5494 ffff880000f0da40 ffff88001275e150 ffffffffa0489477
Aug 28 04:58:19 alpha kernel: [  794.485969]  ffff88003d1b2d20 ffff88003d1b2d40 ffff88003d1b2d20 ffff88003d1b2d48
Aug 28 04:58:19 alpha kernel: [  794.487231] Call Trace:
Aug 28 04:58:19 alpha kernel: [  794.487779]  [<ffffffffa04a5494>] ? eth_vlan_unbind_user_ipcp+0x14/0x70 [shim_eth_vlan]
Aug 28 04:58:19 alpha kernel: [  794.489060]  [<ffffffffa0489477>] ? rmt_destroy+0x97/0x1d0 [rina_personality_default]
Aug 28 04:58:19 alpha kernel: [  794.490611]  [<ffffffffa04c5a15>] ? normal_destroy+0x145/0x200 [normal_ipcp]
Aug 28 04:58:19 alpha kernel: [  794.491478]  [<ffffffffa048f8de>] ? kipcm_ipcp_destroy+0x4e/0xf0 [rina_personality_default]
Aug 28 04:58:19 alpha kernel: [  794.493412]  [<ffffffff81503c8d>] ? SyS_ipc_destroy+0x6d/0xb0
Aug 28 04:58:19 alpha kernel: [  794.494142]  [<ffffffff8152076d>] ? system_call_fastpath+0x1a/0x1f
Aug 28 04:58:19 alpha kernel: [  794.494898] Code: 55 53 48 89 fd 4c 89 ef 41 89 f4 e8 e3 24 07 e1 48 8b 5d 68 48 8d 55 68 48 39 d3 75 0e eb 2c 0f 1f 40 00 48 8b 1b 48 39 d3 74 20 <44> 39 63 20 75 f2 48 89 c6 4c 89 ef e8 97 22 07 e1 48 89 d8 5b
Aug 28 04:58:19 alpha kernel: [  794.497609] RIP  [<ffffffffa04a5448>] find_flow+0x38/0x70 [shim_eth_vlan]
Aug 28 04:58:19 alpha kernel: [  794.498312]  RSP <ffff88003d18beb0>
Aug 28 04:58:19 alpha kernel: [  794.498634] CR2: 0000000000000020
Aug 28 04:58:19 alpha kernel: [  794.499920] ---[ end trace 2dfd0fda7bf9b924 ]---
```

### PR DESCRIPTION
**Pull request by dstaesse**
shim-eth-vlan.c : moved null_ptr check within spinlock, (fixes #721)
                  added null_ptr checks and ASSERTs to other functions,
                  removed eth_vlan prefix from internal functions eth_vlan_update_qdisc and eth_vlan_restore_qdisc

MAINTAINER: @sandervrijders

### CODE REVIEW

File: linux/net/rina/ipcps/shim-eth-vlan.c [hunk 1]
```diff
@@ -270,11 +275,6 @@ find_flow_by_gpa(struct ipcp_instance_data * data,
 
 static bool vlan_id_is_ok(uint16_t vlan_id)
 {
-        if (vlan_id > 4095 /* 0xFFF */) {
-                /* Out of bounds */
-                return false;
-        }
-
         ASSERT(vlan_id <= 4095);
```
Comment (sandervrijders) [inline linux/net/rina/ipcps/shim-eth-vlan.c]: This should remain an if() check, since it is just parsing userspace, and should not crash the kernel, but exit gracefully if the VLAN id is out of bounds.

File: linux/net/rina/ipcps/shim-eth-vlan.c [hunk 2]
```diff
@@ -552,8 +575,15 @@ eth_vlan_flow_allocate_response(struct ipcp_instance_data * data,
         struct shim_eth_flow * flow;
         struct ipcp_instance * ipcp;
 
-        ASSERT(data);
-        ASSERT(is_port_id_ok(port_id));
+       	if (!data) {
```
Comment (sandervrijders) [inline linux/net/rina/ipcps/shim-eth-vlan.c]: Bad indentation

Comment (dstaesse) [inline linux/net/rina/ipcps/shim-eth-vlan.c]: It doesn't look bad in my emacs...

File: linux/net/rina/ipcps/shim-eth-vlan.c [hunk 3]
```diff
@@ -300,13 +301,8 @@ static string_t * create_vlan_interface_name(string_t * interface_name,
...
 
-        if (!interface_name)
-                return NULL;
-
-        if (!vlan_id_is_ok(vlan_id)) {
-                LOG_ERR("Wrong vlan-id %d", vlan_id);
-                return NULL;
-        }
+        ASSERT(interface_name);
+        ASSERT(vlan_id_is_ok(vlan_id));
```
Comment (sandervrijders) [inline linux/net/rina/ipcps/shim-eth-vlan.c]: This will break the regression tests. It makes sense not to assert in this function, but to do checks on the value of the VLAN.

Comment (dstaesse) [inline linux/net/rina/ipcps/shim-eth-vlan.c]: should be fixed now.

**Comment by kewinrausch** [comment]
I'm going to test it in vwall environment. Just a quick question:
```
spin_lock_irqsave(&data->lock, flags);
if (!flow) 
	return -1;

if (flow->user_ipcp) {
	flow->user_ipcp = NULL;
}
spin_unlock_irqrestore(&data->lock, flags);
```

Shouldn't the ```if(!flow)``` do also a ```spin_unlock_irqrestore(&data->lock, flags)``` before the ```return -1;```.

**Comment by sandervrijders** [comment]
Absolutely. That's a bug.

**Comment by dstaesse** [comment]
(facepalm) Thanks for noticing!
Fixed and rebased to single commit.

**Comment by kewinrausch** [comment]
Wait, wait... I wont let you go so easily :P

I have just another problem which happens when you ctrl-c (which seems to go) and then, once updated the DIFs configuration, for example, try again to run the ipcm to recreate the configuration on the machine.

```
Sep  9 11:34:26 alpha kernel: [ 1760.074560] rina-shim-eth-vlan(DBG): [create_vlan_interface_name] Complete vlan-interface-name = 'eth18.100'
Sep  9 11:34:26 alpha kernel: [ 1760.074591] BUG: unable to handle kernel NULL pointer dereference at 0000000000000018
Sep  9 11:34:26 alpha kernel: [ 1760.074623] IP: [<ffffffffa06a6703>] update_qdisc+0x23/0x130 [shim_eth_vlan]
Sep  9 11:34:26 alpha kernel: [ 1760.074641] PGD caaf1067 PUD cb12c067 PMD 0
Sep  9 11:34:26 alpha kernel: [ 1760.074658] Oops: 0000 [#1] SMP
Sep  9 11:34:26 alpha kernel: [ 1760.074669] Modules linked in: normal_ipcp rina_default_plugin shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp mrp llc nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop ohci_pci ohci_hcd ehci_pci ehci_hcd usbcore nouveau snd_pcm mxm_wmi wmi video ttm drm_kms_helper drm shpchp usb_common nv_tco edac_mce_amd i2c_nforce2 i2c_algo_bit edac_core i2c_core k8temp snd_timer snd soundcore processor psmouse parport_pc parport serio_raw pcspkr thermal_sys evdev kvm_amd kvm button ext4 crc16 mbcache jbd2 dm_mod sg sd_mod crc_t10dif crct10dif_common ata_generic e1000e ptp pps_core sata_nv pata_amd forcedeth libata scsi_mod
Sep  9 11:34:26 alpha kernel: [ 1760.074934] CPU: 3 PID: 8778 Comm: ipcm Not tainted 3.15.0-pristine-1.3 #5
Sep  9 11:34:26 alpha kernel: [ 1760.074944] Hardware name: Supermicro H8DMR-82/H8DMR-82, BIOS 080014  04/01/2008
Sep  9 11:34:26 alpha kernel: [ 1760.074955] task: ffff8800cfa16b60 ti: ffff8800cae44000 task.ti: ffff8800cae44000
Sep  9 11:34:26 alpha kernel: [ 1760.074964] RIP: 0010:[<ffffffffa06a6703>]  [<ffffffffa06a6703>] update_qdisc+0x23/0x130 [shim_eth_vlan]
Sep  9 11:34:26 alpha kernel: [ 1760.074987] RSP: 0018:ffff8800cae47a10  EFLAGS: 00010282
Sep  9 11:34:26 alpha kernel: [ 1760.074995] RAX: 0000000000000000 RBX: ffff88007b278000 RCX: 0000000000000000
Sep  9 11:34:26 alpha kernel: [ 1760.075004] RDX: ffff8800cabbf4c0 RSI: ffffffffa06ab190 RDI: ffff88007b278000
Sep  9 11:34:26 alpha kernel: [ 1760.075014] RBP: 000000000000000f R08: 0000000000000000 R09: 00000000fffffffe
Sep  9 11:34:26 alpha kernel: [ 1760.075023] R10: 0000000000000000 R11: 00000000002d7475 R12: ffff8800cabbf4c0
Sep  9 11:34:26 alpha kernel: [ 1760.075032] R13: ffff88012c4766e0 R14: ffffffffa06aa05e R15: ffff8800cf92fd00
Sep  9 11:34:26 alpha kernel: [ 1760.075042] FS:  00007f48bdf4c740(0000) GS:ffff88012fc80000(0000) knlGS:0000000000000000
Sep  9 11:34:26 alpha kernel: [ 1760.075052] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep  9 11:34:26 alpha kernel: [ 1760.075060] CR2: 0000000000000018 CR3: 00000000cf917000 CR4: 00000000000007e0
Sep  9 11:34:26 alpha kernel: [ 1760.075068] Stack:
Sep  9 11:34:26 alpha kernel: [ 1760.075073]  ffffffffa06a50b4 ffff8800caf84180 000000000000000f ffff8800cabbf4c0
Sep  9 11:34:26 alpha kernel: [ 1760.075089]  ffff88012c4766e0 ffffffffa06a6e44 ffff8800cf9c0a30 00000064a06922f0
Sep  9 11:34:26 alpha kernel: [ 1760.075105]  ffff8800cae47b00 ffff88012bb4cd00 0000000000000001 ffff88012f442840
Sep  9 11:34:26 alpha kernel: [ 1760.075121] Call Trace:
Sep  9 11:34:26 alpha kernel: [ 1760.075130]  [<ffffffffa06a50b4>] ? create_vlan_interface_name+0xe4/0xf0 [shim_eth_vlan]
Sep  9 11:34:26 alpha kernel: [ 1760.075142]  [<ffffffffa06a6e44>] ? eth_vlan_assign_to_dif+0x234/0x516 [shim_eth_vlan]
Sep  9 11:34:26 alpha kernel: [ 1760.075160]  [<ffffffffa068d18b>] ? notify_ipcp_assign_dif_request+0xcb/0x190 [rina_personality_default]
Sep  9 11:34:26 alpha kernel: [ 1760.075174]  [<ffffffffa068d0c0>] ? notify_ipcp_allocate_flow_response+0x210/0x210 [rina_personality_default]
Sep  9 11:34:26 alpha kernel: [ 1760.075188]  [<ffffffff814fd373>] ? dispatcher+0x153/0x1f0
Sep  9 11:34:26 alpha kernel: [ 1760.075200]  [<ffffffff814437c3>] ? genl_family_rcv_msg+0x193/0x360
Sep  9 11:34:26 alpha kernel: [ 1760.075210]  [<ffffffff81443990>] ? genl_family_rcv_msg+0x360/0x360
Sep  9 11:34:26 alpha kernel: [ 1760.075219]  [<ffffffff81443a09>] ? genl_rcv_msg+0x79/0xc0
Sep  9 11:34:26 alpha kernel: [ 1760.075229]  [<ffffffff81443100>] ? netlink_rcv_skb+0xa0/0xc0
Sep  9 11:34:26 alpha kernel: [ 1760.075238]  [<ffffffff81443614>] ? genl_rcv+0x24/0x40
Sep  9 11:34:26 alpha kernel: [ 1760.075247]  [<ffffffff8144274c>] ? netlink_unicast+0xfc/0x190
Sep  9 11:34:26 alpha kernel: [ 1760.075256]  [<ffffffff81442b0e>] ? netlink_sendmsg+0x32e/0x770
Sep  9 11:34:26 alpha kernel: [ 1760.075268]  [<ffffffff813fbc4d>] ? sock_sendmsg+0x8d/0xc0
Sep  9 11:34:26 alpha kernel: [ 1760.075583]  [<ffffffff8109bff1>] ? check_preempt_wakeup+0x151/0x1d0
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff8119635e>] ? __mem_cgroup_commit_charge+0x7e/0x390
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff813fb989>] ? move_addr_to_kernel.part.19+0x19/0x60
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff813fc0d8>] ? ___sys_sendmsg+0x408/0x420
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff8136740c>] ? pty_write+0x4c/0x50
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff810a46d2>] ? remove_wait_queue+0x12/0x50
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff8151b780>] ? __do_page_fault+0x220/0x520
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff81098816>] ? set_next_entity+0x56/0x70
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff8109fab8>] ? pick_next_task_fair+0x6c8/0x820
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff81011616>] ? __switch_to+0x196/0x4f0
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff813fce7e>] ? __sys_sendmsg+0x3e/0x80
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  [<ffffffff8152076d>] ? system_call_fastpath+0x1a/0x1f
Sep  9 11:34:26 alpha kernel: [ 1760.076026] Code: fd ff ff 0f 1f 44 00 00 66 66 66 66 90 41 55 41 54 48 c7 c6 90 b1 6a a0 55 53 48 89 fb 49 89 d4 48 83 ec 08 48 8b 87 90 03 00 00 <48> 8b 78 18 48 83 c7 10 e8 50 12 e5 e0 85 c0 89 c5 75 12 48 83
Sep  9 11:34:26 alpha kernel: [ 1760.076026] RIP  [<ffffffffa06a6703>] update_qdisc+0x23/0x130 [shim_eth_vlan]
Sep  9 11:34:26 alpha kernel: [ 1760.076026]  RSP <ffff8800cae47a10>
Sep  9 11:34:26 alpha kernel: [ 1760.076026] CR2: 0000000000000018
Sep  9 11:34:26 alpha kernel: [ 1760.084167] ---[ end trace 5a8c5ec423877965 ]---
```

Booom! :bomb:

**Comment by dstaesse** [comment]
This was not introduced in this PR. However, looks like the qdisc was destroyed before the shim.
Can you test this patch?

**Comment by dstaesse** [comment]
@sandervrijders: fixed merge conflicts and rebased

**Comment by sandervrijders** [comment]
@kewinrausch Can you ACK that the PR is working? How have you tested it (scenario)?

**Comment by kewinrausch** [comment]
@sandervrijders: Yes, ACKed. 

I tested it in a vwall scenario with 4 nodes(even thus 2 node scenario is enough), and that oops is no more occurred.

**Comment by sandervrijders** [comment]
ACK
