### PR TITLE
kernel: shim-tcp-udp: pass port-id as application process instance of…

### LINKED ISSUE #909: Can't make an IPCP enroll to several neighbours
With a single shim-tcp-udp to link more than 2 machines, there are cases where making each node a neighbour of all other machines (full-mesh) fail.

Given 3 VMs setup as follows: VM0 -> VM1 -> VM2 where "->" is an enrollment
VM0 -> VM2 then fails (after the TCP connection is established successfully), whereas VM2 -> VM0 succeeds.

Here are logs from VM2:

>  # VM1 -> VM2
> 290(1460111733)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between vm2.IRATI:1:: and Unknown app:::
> 290(1460111733)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process shim2:1:: about flow allocation from application vm2.IRATI:1:: to application Unknown app::: in DIF shim::: [success = 1, port-id = 1]
>
>  # VM0 -> VM2
> 290(1460111735)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between vm2.IRATI:1:: and Unknown app:::
> 290(1460111735)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process shim2:1:: about flow allocation from application vm2.IRATI:1:: to application Unknown app::: in DIF shim::: [success = 0, port-id = -1]

### PR DESCRIPTION
**Pull request by edugrasa**
Differentiate between multiple instance of "Unknown app" in the shim TCP-UDP. Fixes #909 

Maintainer: @sandervrijders 
@jmuchemb could you test it? Thanks!

### CODE REVIEW

**Comment by jmuchemb** [comment]
Don't you have a memory leak with api_string ? Why not using the stack as a buffer ?

**Comment by edugrasa** [comment]
I don't think there is a memory leak, the memory pointed by api_string is released when the "name" structure is destroyed

**Comment by edugrasa** [comment]
@jmuchemb thanks for pointing at this, fix pushed!

**Comment by jmuchemb** [comment]
This fixes #909 for me.

**Comment by dstaesse** [comment]
we added it to the application name with sprintf, not as the application instance, but this will probably work as well.

File: linux/net/rina/ipcps/shim-tcp-udp.c [hunk 1]
```diff
@@ -1032,6 +1032,22 @@ int send_msg(struct socket *      sock,
         return size;
 }
 
+char * tcp_udp_int_to_string(int data)
+{
+	char * result;
+
+        result = rkmalloc(10, GFP_ATOMIC);
```
Comment (dstaesse) [inline linux/net/rina/ipcps/shim-tcp-udp.c]: 10 characters is usually plenty, but an int may need 12 (one for the - sign, 10 for the number and one for the \0)

File: linux/net/rina/ipcps/shim-tcp-udp.c [hunk 2]
```diff
@@ -1032,6 +1032,22 @@ int send_msg(struct socket *      sock,
...
+        if(!result)
+                return NULL;
+
+        if (sprintf(result, "%d\n", data) < 0) {
```
Comment (dstaesse) [inline linux/net/rina/ipcps/shim-tcp-udp.c]: why the \n?

**Comment by edugrasa** [comment]
@dstaesse Thanks for the feedback! Polished a few details as suggested.

**Comment by sandervrijders** [comment]
ACK. Haven't tested though, but if there are no regressions since @jmuchemb tested it, it can be merged.
