### PR TITLE
Fix #517: cleanup of IPCP kernel state when detecting a crashed IPCP Daemon OS Process

### LINKED ISSUE #517: Cleanup IPCP kernel state when detecting that an IPCP Daemon has crashed
The IPCM should cleanup the IPCP kernel state when it detects that an IPCP Daemon has crashed (unless the IPCM is also shutting down).

### PR DESCRIPTION
**Pull request by edugrasa**
Sorry, forgot to create a separate branch to address the issue. The fix is tested.

### CODE REVIEW

File: rinad/src/ipcm/app-handlers.cc [hunk 1]
```diff
@@ -47,61 +47,68 @@ void IPCManager_::os_process_finalized_handler(
...
 
-		{
-			//Auto release the read lock
-			rina::ReadScopedLock readlock(ipcp->rwlock, false);
-			ipcp_id = ipcp->get_id();
-		}
+			{
+				//Auto release the read lock
+				rina::ReadScopedLock readlock(ipcp->rwlock, false);
+				ipcp_id = ipcp->get_id();
```
Comment (vmaffione) [inline rinad/src/ipcm/app-handlers.cc]: This lock idiom is not correct - in general. You assign the local variable under the lock, but then you use it outside the lock (line 77): when you use it, the ipcp->get_id() value may have already been changed under your feet. Is that what you want? I know that the ipcp id should not change, but then why you need a lock to access the ipcp id?

Comment (msune) [inline rinad/src/ipcm/app-handlers.cc]: As far as I can see, it is correct.

The call to `IPCManager->deallocate_flow()` cannot be done with the IPCP readlock acquired or it will dead-lock. If the IPCP ID has changed the call will fail and that's it (the destruction will anyway deallocate the flow).

This line:
`rina::ReadScopedLock readlock(ipcp->rwlock, false);` is NOT acquiring the lock, but rather uses RAII to unlock the previously acquired rwlock in `select_ipcp_by_dif()` (the second parameter, set to false, indicates do not lock).

Comment (edugrasa) [inline rinad/src/ipcm/app-handlers.cc]: Yes, it is correct.

Comment (vmaffione) [inline rinad/src/ipcm/app-handlers.cc]: Right. Now that I've really examined it, I get that you use the ipcp->rwlock also as a reference counter - you get a reference in select_ipcp_by_dif and release it with that line. It's ok, but isn't that a bit obscure for the code reader?
Maybe we need some wrapper functions with more explicit names, like ``ipcp->read_get(), ipcp->read_put(), ipcp->write_get(), ipcp->write_put()``. Otherwise it is obscure - at least for me.

Comment (vmaffione) [inline rinad/src/ipcm/app-handlers.cc]: Right. Now that I've really examined it, I get that you use the ipcp->rwlock also as a reference counter - you get a reference in select_ipcp_by_dif and release it with that line. It's ok, but isn't that a bit obscure for the code reader?
Maybe we need some wrapper functions with more explicit names, like ``ipcp->read_get(), ipcp->read_put(), ipcp->write_get(), ipcp->write_put()``. Otherwise it is obscure - at least for me.

Comment (edugrasa) [inline rinad/src/ipcm/app-handlers.cc]: Vincenzo, this is pull request is about a minor fix to improve the stability of the current IPCM. The former pull request (aka the monster) was using this design extensively (in almost all the functions). The code in this pull request just follows the same design that is already there. 

We can discuss if it needs to improved and be made less obscure, but this would be another IPCM refactor. Therefore I would just merge this humble pull request in, which will make the live of people using the stack a bit easier ;)

Comment (vmaffione) [inline rinad/src/ipcm/app-handlers.cc]: Yes, agree.
